// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignment_grades.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAssignmentGrades = `-- name: CreateAssignmentGrades :one
INSERT INTO assignment_grades (
  assignment_grades_id,
  assignment_id,
  user_id
)
VALUES (
  gen_random_uuid(),
  $1,
  $2
)
RETURNING assignment_grades_id, assingmnet_grade, user_id, assignment_id
`

type CreateAssignmentGradesParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateAssignmentGrades(ctx context.Context, arg CreateAssignmentGradesParams) (AssignmentGrade, error) {
	row := q.db.QueryRowContext(ctx, createAssignmentGrades, arg.AssignmentID, arg.UserID)
	var i AssignmentGrade
	err := row.Scan(
		&i.AssignmentGradesID,
		&i.AssingmnetGrade,
		&i.UserID,
		&i.AssignmentID,
	)
	return i, err
}
