// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAssignments = `-- name: CreateAssignments :one
INSERT INTO assignments (
  assignments_id,
  created_at,
  updated_at,
  assignment_name,
  assignment_due_date,
  assignment_description,
  assignment_weight,
  course_id
)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING assignments_id, created_at, updated_at, assignment_name, assignment_due_date, assignment_description, assignment_weight, course_id
`

type CreateAssignmentsParams struct {
	AssignmentName        string    `json:"assignment_name"`
	AssignmentDueDate     time.Time `json:"assignment_due_date"`
	AssignmentDescription string    `json:"assignment_description"`
	AssignmentWeight      int32     `json:"assignment_weight"`
	CourseID              uuid.UUID `json:"course_id"`
}

func (q *Queries) CreateAssignments(ctx context.Context, arg CreateAssignmentsParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignments,
		arg.AssignmentName,
		arg.AssignmentDueDate,
		arg.AssignmentDescription,
		arg.AssignmentWeight,
		arg.CourseID,
	)
	var i Assignment
	err := row.Scan(
		&i.AssignmentsID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentName,
		&i.AssignmentDueDate,
		&i.AssignmentDescription,
		&i.AssignmentWeight,
		&i.CourseID,
	)
	return i, err
}
