// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course_enrollment.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCourseEnrollment = `-- name: CreateCourseEnrollment :one
INSERT INTO course_enrollment (
  enrollment_id,
  course_id,
  user_id
)
VALUES (
  gen_random_uuid(),
  $1,
  $2
)
RETURNING enrollment_id, final_grade, course_id, user_id
`

type CreateCourseEnrollmentParams struct {
	CourseID uuid.UUID `json:"course_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateCourseEnrollment(ctx context.Context, arg CreateCourseEnrollmentParams) (CourseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, createCourseEnrollment, arg.CourseID, arg.UserID)
	var i CourseEnrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.FinalGrade,
		&i.CourseID,
		&i.UserID,
	)
	return i, err
}
