// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	LastName        string    `json:"last_name"`
	FirstName       string    `json:"first_name"`
	Username        string    `json:"username"`
	PersonalEmail   string    `json:"personal_email"`
	UniversityEmail string    `json:"university_email"`
	Isadmin         bool      `json:"isadmin"`
	Password        string    `json:"password"`
}
