// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assignment struct {
	AssignmentsID         uuid.UUID `json:"assignments_id"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	AssignmentName        string    `json:"assignment_name"`
	AssignmentDueDate     time.Time `json:"assignment_due_date"`
	AssignmentDescription string    `json:"assignment_description"`
}

type Course struct {
	CoursesID         uuid.UUID `json:"courses_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	CourseCode        string    `json:"course_code"`
	CourseName        string    `json:"course_name"`
	CourseDescription string    `json:"course_description"`
	CourseProfessorID uuid.UUID `json:"course_professor_id"`
}

type DegreeProgram struct {
	DegreesID        uuid.UUID `json:"degrees_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DegreeName       string    `json:"degree_name"`
	DegreeLevel      string    `json:"degree_level"`
	DegreeDepartment string    `json:"degree_department"`
	DegreeDuration   int16     `json:"degree_duration"`
}

type DegreesCourse struct {
	DegreesCoursesID uuid.UUID `json:"degrees_courses_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DegreeID         uuid.UUID `json:"degree_id"`
	CourseID         uuid.UUID `json:"course_id"`
}

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	RolesID  uuid.UUID `json:"roles_id"`
	RoleName string    `json:"role_name"`
}

type User struct {
	UsersID         uuid.UUID `json:"users_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	LastName        string    `json:"last_name"`
	FirstName       string    `json:"first_name"`
	Username        string    `json:"username"`
	PersonalEmail   string    `json:"personal_email"`
	UniversityEmail string    `json:"university_email"`
	Password        string    `json:"password"`
}

type UsersProgram struct {
	UsersProgramID uuid.UUID `json:"users_program_id"`
	CohortYear     int32     `json:"cohort_year"`
	StartDate      time.Time `json:"start_date"`
	StudentID      uuid.UUID `json:"student_id"`
	ProgramID      uuid.UUID `json:"program_id"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
}

type UsersRole struct {
	UsersRolesID uuid.UUID `json:"users_roles_id"`
	UserID       uuid.UUID `json:"user_id"`
	RoleID       uuid.UUID `json:"role_id"`
}

type Year struct {
	YearsID      uuid.UUID `json:"years_id"`
	YearInSchool int16     `json:"year_in_school"`
}
