// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	RolesID  uuid.UUID `json:"roles_id"`
	RoleName string    `json:"role_name"`
}

type User struct {
	UsersID         uuid.UUID `json:"users_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	LastName        string    `json:"last_name"`
	FirstName       string    `json:"first_name"`
	Username        string    `json:"username"`
	PersonalEmail   string    `json:"personal_email"`
	UniversityEmail string    `json:"university_email"`
	Password        string    `json:"password"`
}

type UsersRole struct {
	UsersRolesID uuid.UUID `json:"users_roles_id"`
	UserID       uuid.UUID `json:"user_id"`
	RoleID       uuid.UUID `json:"role_id"`
}
