// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const resetAssignmentGrades = `-- name: ResetAssignmentGrades :exec
DELETE FROM assignment_grades
`

func (q *Queries) ResetAssignmentGrades(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAssignmentGrades)
	return err
}

const resetAssignments = `-- name: ResetAssignments :exec
DELETE FROM assignments
`

func (q *Queries) ResetAssignments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAssignments)
	return err
}

const resetCourseEnrollment = `-- name: ResetCourseEnrollment :exec
DELETE FROM course_enrollment
`

func (q *Queries) ResetCourseEnrollment(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCourseEnrollment)
	return err
}

const resetCourses = `-- name: ResetCourses :exec
DELETE FROM courses
`

func (q *Queries) ResetCourses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCourses)
	return err
}

const resetDegrees = `-- name: ResetDegrees :exec
DELETE FROM degree_programs
`

func (q *Queries) ResetDegrees(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDegrees)
	return err
}

const resetDegreesCourses = `-- name: ResetDegreesCourses :exec
DELETE FROM degrees_courses
`

func (q *Queries) ResetDegreesCourses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDegreesCourses)
	return err
}

const resetRoles = `-- name: ResetRoles :exec
DELETE FROM roles
`

func (q *Queries) ResetRoles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRoles)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}

const resetUsersPrograms = `-- name: ResetUsersPrograms :exec
DELETE FROM users_programs
`

func (q *Queries) ResetUsersPrograms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsersPrograms)
	return err
}

const resetUsersRoles = `-- name: ResetUsersRoles :exec
DELETE FROM users_roles
`

func (q *Queries) ResetUsersRoles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsersRoles)
	return err
}

const resetYears = `-- name: ResetYears :exec
DELETE FROM years
`

func (q *Queries) ResetYears(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetYears)
	return err
}
