// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  id,
  role_name
)
VALUES (
  gen_random_uuid(),
  $1
)
RETURNING id, role_name
`

func (q *Queries) CreateRole(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, roleName)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName)
	return i, err
}
