// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  roles_id,
  role_name
)
VALUES (
  gen_random_uuid(),
  $1
)
RETURNING roles_id, role_name
`

func (q *Queries) CreateRole(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, roleName)
	var i Role
	err := row.Scan(&i.RolesID, &i.RoleName)
	return i, err
}

const getSingleRole = `-- name: GetSingleRole :one
SELECT roles_id, role_name FROM roles
WHERE role_name = $1
`

func (q *Queries) GetSingleRole(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getSingleRole, roleName)
	var i Role
	err := row.Scan(&i.RolesID, &i.RoleName)
	return i, err
}
