// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUsersRoles = `-- name: CreateUsersRoles :one
INSERT INTO users_roles (
  users_roles_id,
  user_id,
  role_id
)
VALUES (
  gen_random_uuid(),
  $1,
  $2
)
RETURNING users_roles_id, user_id, role_id
`

type CreateUsersRolesParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) CreateUsersRoles(ctx context.Context, arg CreateUsersRolesParams) (UsersRole, error) {
	row := q.db.QueryRowContext(ctx, createUsersRoles, arg.UserID, arg.RoleID)
	var i UsersRole
	err := row.Scan(&i.UsersRolesID, &i.UserID, &i.RoleID)
	return i, err
}
