// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    created_at,
    updated_at,
    last_name,
    first_name,
    username,
    personal_email,
	university_email,
    isStudent,
	isAdmin,
    password
)
Values (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
	$6,
	$7,
    $8
)
RETURNING id, created_at, updated_at, last_name, first_name, username, personal_email, university_email, isstudent, isadmin, password
`

type CreateUserParams struct {
	LastName        string `json:"last_name"`
	FirstName       string `json:"first_name"`
	Username        string `json:"username"`
	PersonalEmail   string `json:"personal_email"`
	UniversityEmail string `json:"university_email"`
	Isstudent       bool   `json:"isstudent"`
	Isadmin         bool   `json:"isadmin"`
	Password        string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.LastName,
		arg.FirstName,
		arg.Username,
		arg.PersonalEmail,
		arg.UniversityEmail,
		arg.Isstudent,
		arg.Isadmin,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastName,
		&i.FirstName,
		&i.Username,
		&i.PersonalEmail,
		&i.UniversityEmail,
		&i.Isstudent,
		&i.Isadmin,
		&i.Password,
	)
	return i, err
}

const login = `-- name: Login :one
SELECT id, created_at, updated_at, last_name, first_name, username, personal_email, university_email, isstudent, isadmin, password FROM users
WHERE username = $1
`

func (q *Queries) Login(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, login, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastName,
		&i.FirstName,
		&i.Username,
		&i.PersonalEmail,
		&i.UniversityEmail,
		&i.Isstudent,
		&i.Isadmin,
		&i.Password,
	)
	return i, err
}
