// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_internships.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserInternships = `-- name: CreateUserInternships :one
INSERT INTO user_internships (
  user_internships_id,
  user_id,
  internship_id
)
VALUES (
  gen_random_uuid(),
  $1,
  $2
)
RETURNING user_internships_id, user_id, internship_id
`

type CreateUserInternshipsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	InternshipID uuid.UUID `json:"internship_id"`
}

func (q *Queries) CreateUserInternships(ctx context.Context, arg CreateUserInternshipsParams) (UserInternship, error) {
	row := q.db.QueryRowContext(ctx, createUserInternships, arg.UserID, arg.InternshipID)
	var i UserInternship
	err := row.Scan(&i.UserInternshipsID, &i.UserID, &i.InternshipID)
	return i, err
}
