// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: years.sql

package database

import (
	"context"
)

const createYears = `-- name: CreateYears :one
INSERT INTO years (
  years_id,
  year_in_school
)
VALUES (
  gen_random_uuid(),
  $1
)
RETURNING years_id, year_in_school
`

func (q *Queries) CreateYears(ctx context.Context, yearInSchool int16) (Year, error) {
	row := q.db.QueryRowContext(ctx, createYears, yearInSchool)
	var i Year
	err := row.Scan(&i.YearsID, &i.YearInSchool)
	return i, err
}
